<?php

    $modelSiteMenu = new Model_DbTable_SiteMenu();
    $menus = $modelSiteMenu->fetchAll();

?>
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a href="<?php echo $this->url(array(
                'module' => "site",
                'controller' => "index",
                'action' => "index"
            ), null, true); ?>">
                StyleSheets::Admin
            </a>
        </li>
        <?php if ($menus->count() > 0 && Zend_Auth::getInstance()->hasIdentity()) : foreach ($menus as $menu) : ?>
        <li>
            <a href="<?php echo $this->url(array(
                'module' => $menu->site_menu_module,
                'controller' => $menu->site_menu_controller,
                'action' => $menu->site_menu_action
            ), null, true); ?>"><?php echo $menu->site_menu_label; ?></a>
        </li>
        <?php endforeach; endif; ?>
    </ul>
</div>
<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
<a id="menu-close" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-times"></i></a>
<!-- /#sidebar-wrapper -->