<?php

    $modelSiteMenu = new Model_DbTable_SiteMenu();
    $menus = $modelSiteMenu->fetchAll("site_menu_ativo = 1", "site_menu_ordem asc");

?>
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand" style="padding: 7px 15px;">
            <a href="<?php echo $this->url(array(
                'module' => "site",
                'controller' => "index",
                'action' => "index"
            ), null, true); ?>">
                <img style="background: #FFF; padding: 7px;" src="<?php echo $this->baseUrl('views/img/logo.png'); ?>" width="200" class="img img-responsive" />
            </a>
        </li>
        <?php if ($menus->count() > 0 && Zend_Auth::getInstance()->hasIdentity()) : foreach ($menus as $menu) : ?>
        <li>
            <a href="<?php echo $this->url(array(
                'module' => $menu->site_menu_module,
                'controller' => $menu->site_menu_controller,
                'action' => $menu->site_menu_action
            ), null, true); ?>">
                <i class="<?php echo $menu->site_menu_icon; ?>"></i>
                <?php echo $menu->site_menu_label; ?>
            </a>
        </li>
        <?php endforeach; endif; ?>
    </ul>
</div>
<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
<!-- /#sidebar-wrapper -->