<section>
    
    <div class="row">
        <div class="col-lg-12">
            <h3>Cliente Detalhes</h3>   
        </div>
    </div>
    
    <!-- ACOES -->
    <div class="row">
        <div class="col-lg-12 text-right">            
            <a href="<?php echo $this->url(array(
                'controller' => 'cliente',
                'action' => 'editar',
                'cliente' => $this->cliente->cliente_id
            ), null, true); ?>" class="btn btn-sm btn-info"><i class="fa fa-edit fa-2x"></i></a>
            <!--
            <a href="<?php echo $this->url(array(
                'controller' => 'cliente',
                'action' => 'excluir',
                'cliente' => $this->cliente->cliente_id
            ), null, true); ?>" class="btn btn-sm btn-danger"><i class="fa fa-trash fa-2x"></i></a> 
            -->
            <?php if (!$this->cliente->cliente_acesso) : ?>
            <a href="<?php echo $this->url(array(
                
            ), null, true); ?>" class="btn btn-sm btn-warning"><i class="fa fa-send fa-2x"></i></a>            
            <?php endif; ?>
            <hr />
        </div>
    </div>    
    
    <!-- DETALHES DO REGISTRO -->
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">Dados do Cliente</div>
                <div class="panel-body">
                    <p><b>Tipo: </b><?php echo $this->cliente->cliente_tipo; ?></p>
                    <?php if ($this->cliente->cliente_empresa) : ?>
                    <p><b>Empresa: </b><?php echo $this->cliente->cliente_empresa; ?></p>
                    <p><b>CNPJ: </b><?php echo $this->cliente->cliente_cpf_cnpj; ?></p>
                    <?php else : ?>
                    <p><b>CPF: </b><?php echo $this->cliente->cliente_cpf_cnpj; ?></p>
                    <?php endif; ?>
                    <p><b>Contato: </b><?php echo $this->cliente->cliente_nome; ?></p>
                    <p><b>E-mail: </b><?php echo $this->cliente->cliente_email; ?></p>
                    <p><b>Telefone: </b><?php echo $this->cliente->cliente_telefone; ?></p>
                    <p><b>Celular: </b><?php echo $this->cliente->cliente_celular; ?></p>
                    <p><b>Endereco: </b>
                        <?php echo $this->cliente->cliente_endereco ? $this->cliente->cliente_endereco : ''; ?>
                        <?php echo $this->cliente->cliente_numero ? ', '.$this->cliente->cliente_numero : ''; ?>
                        <?php echo $this->cliente->cliente_complemento ? ' - ' .$this->cliente->cliente_complemento: ''; ?>
                        <?php echo $this->cliente->cliente_bairro ? ' - '.$this->cliente->cliente_bairro : ''; ?>
                        <?php echo $this->cliente->cliente_cidade ? ' - '.$this->cliente->cliente_cidade : ''; ?>
                        <?php echo $this->cliente->cliente_estado ? '/'.$this->cliente->cliente_estado : ''; ?>
                    </p>
                    <?php if ($this->cliente->cliente_acesso) : ?>                    
                    <p><b>Último acesso: </b></p>
                    <?php else : ?>
                    <p><b>Último acesso: </b> Não tem acesso</p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading">Controle de Horas</div>
                <div class="panel-body text-center">
                    <h4>Total Horas Trabalhadas:</h4>
                    <h4>55</h4>
                </div>
            </div>            
            <div class="panel panel-default">
                <div class="panel-heading">Propostas <span class="badge"><?php echo $this->propostas->count(); ?></span></div>
                <div class="panel-body">
                    <p><b>Aguardando resposta:</b></p>
                    <p><b>Aprovada:</b></p>
                    <p><b>Vencida:</b></p>
                </div>
            </div>            
        </div>
        <div class="col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading">Faturamento</div>
                <div class="panel-body text-center">
                    <h4>Total Faturado:</h4>
                    <h4><?php echo $this->currency($this->total_faturado); ?></h4>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Projetos <span class="badge"><?php echo $this->projetos->count(); ?></span></div>
                <div class="panel-body">
                    <p><b>Em desenvolvimento:</b></p>
                    <p><b>Trabalhando:</b></p>
                    <p><b>Pausado:</b></p>
                    <p><b>Entregue:</b></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            
        </div>
    </div>
    
   
    
</section>