<section>
    
    <div class="row">
        <div class="col-lg-12">
            <h3>Cliente Detalhes</h3>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-12 text-right">
            <hr />
            <a href="<?php echo $this->url(array(
                
            ), null, true); ?>" class="btn btn-sm btn-info"><i class="fa fa-edit"></i> Editar</a>
            <a href="<?php echo $this->url(array(
                
            ), null, true); ?>" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Excluir</a>            
        </div>
    </div>
    
</section>