<section>
    <form method="post" action="cliente/cadastro" id="form-cliente-cadastro">
        <div class="row">
            <div class="form-group">
                <div class="col-lg-12"><?php echo $this->formClienteCadastro->cliente_tipo; ?></div>
            </div>
            <div class="form-group">
                <div class="col-lg-6"><?php echo $this->formClienteCadastro->cliente_empresa; ?></div>
                <div class="col-lg-6"><?php echo $this->formClienteCadastro->cliente_nome; ?></div>
            </div>
            <div class="form-group">
                <div class="col-lg-12"><?php echo $this->formClienteCadastro->cliente_email; ?></div>
            </div>
            <div class="form-group">
                <div class="col-lg-6"><?php echo $this->formClienteCadastro->cliente_telefone; ?></div>
                <div class="col-lg-6"><?php echo $this->formClienteCadastro->cliente_celular; ?></div>
            </div>
            <div class="form-group">
                <div class="col-lg-6"><?php echo $this->formClienteCadastro->cliente_cidade; ?></div>
                <div class="col-lg-6"><?php echo $this->formClienteCadastro->cliente_estado; ?></div>
            </div>
            <div class="form-group">
                <div class="col-lg-12"><?php echo $this->formClienteCadastro->submit; ?></div>
            </div>
        </div>    
    </form>
</section>
