<section>
    
    <div class="row">
        <div class="col-lg-12">
            <h3>Controle de Horas</h3>
        </div>
    </div>
    
    <!-- LISTA DE PROJETOS -->
    <div class="row">
        <div class="col-lg-12">
            <?php if ($this->projetos->getCurrentItemCount() > 0) : ?>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-3">Nome</th>
                            <th class="col-md-3">Cliente</th>
                            <th class="col-md-3 text-left">Horas do Projeto</th>
                            <th class="col-md-2 text-center">Status</th>
                            <th class="col-md-1 text-center"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->projetos as $projeto) : //Zend_Debug::dump($projeto); ?>
                        <tr>
                            <td><?php echo $projeto['projeto_nome']; ?></td>                            
                            <td>
                                <?php
                                    if ($projeto['cliente_tipo'] === 'PF') {
                                        echo $projeto['cliente_nome'];
                                    } else {
                                        echo $projeto['cliente_empresa'].' / '.$projeto['cliente_nome'];
                                    }
                                ?>
                            </td>
                            <td>
                                <?php $andamento = $this->andamento($projeto['projeto_id']); ?>
                                <span class="small text-muted"><?php echo $andamento; ?>% Utilizado</span>
                                <div class="progress">                                    
                                    <div 
                                        class="progress-bar progress-bar-success progress-bar-striped" 
                                        role="progressbar" 
                                        aria-valuenow="<?php echo $andamento; ?>" 
                                        aria-valuemin="0" 
                                        aria-valuemax="100" 
                                        style="width: <?php echo $andamento; ?>%"
                                    ></div>
                                </div>
                            </td>
                            <td class="text-center"><?php echo $projeto['projeto_status']; ?></td>                            
                            <td class="text-center">
                                <?php if ($projeto['projeto_status'] !== "Trabalhando") : ?>
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'controle-horas',
                                    'action' => 'play',
                                    'projeto_id' => $projeto['projeto_id']
                                ), null, true); ?>" class="text-success"><i class="fa fa-play fa-2x"></i></a>
                                <?php else : ?>
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'controle-horas',
                                    'action' => 'pause',
                                    'projeto_id' => $projeto['projeto_id']
                                ), null, true); ?>"><i class="fa fa-pause fa-2x"></i></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>                    
                </table>
                <?php echo $this->paginationControl($this->projetos, 'Sliding', 'partials/pagination.phtml'); ?>
            </div>
            <?php else : ?>
            <div class="alert alert-warning">Nenhuma projeto cadastrado</div>            
            <?php endif; ?>
        </div>
    </div>
    
</section>