<?php if ($this->pageCount && $this->pageCount > 1): ?>
<nav>
    <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>"><<</a></li>
        <?php else: ?>
            <li><span><<</span></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>            
            <li class="<?php echo ($page === $this->current) ? 'active' : ''; ?>"><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>            
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">>></a></li>
        <?php else: ?>
            <li><span>>></span></li>
        <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>
 
