<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Intranet::Stylesheets</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $this->baseUrl("views/css/bootstrap.min.css"); ?>" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $this->baseUrl("views/css/simple-sidebar.css"); ?>" rel="stylesheet">
    
    <!-- Custom Fonts -->
    <link href="<?php echo $this->baseUrl("views/css/font-awesome.min.css"); ?>" rel="stylesheet" type="text/css">
    
    <!-- Custom CSS -->
    <link href="<?php echo $this->baseUrl("views/css/style.css"); ?>" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->        
        <?php echo $this->partial("partials/menu.phtml"); ?>        
        
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <!-- Messages -->    
                <?php echo $this->messages; ?> 
                <?php echo $this->layout()->content; ?>                
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src=<?php echo $this->baseUrl("views/js/jquery.min.js"); ?>></script>

    <!-- Bootstrap Core JavaScript -->
    <script src=<?php echo $this->baseUrl("views/js/bootstrap.min.js"); ?>></script>
    
    <!-- MaskedInput Core JavaScript -->
    <script src=<?php echo $this->baseUrl("views/js/jquery.maskedinput.js"); ?>></script>
    
    <!-- Application JavaScript -->
    <script src=<?php echo $this->baseUrl("views/js/application.js"); ?>></script>

    <?php echo $this->headScript(); ?>
    
    <!-- Menu Toggle Script -->
    <script>        
        $("#menu-toggle").hide();   
        
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            $("#menu-close").show();
            $("#menu-toggle").hide();
        });        
        
        // Closes the sidebar menu
        $("#menu-close").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            $("#menu-close").hide();
            $("#menu-toggle").show();
        });
    </script>

</body>

</html>