<section>
    
    <div class="row">
        <div class="col-lg-12">
            <h3>Projetos</h3>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-6">
            <form method="get">
                <div class="form-group">
                    <input type="text" name="projeto_busca" id="projeto_busca" class="form-control" placeholder="Pesquisar projetos" />
                </div>
            </form>
        </div>
        
        <!-- NOVO CLIENTE MODAL -->
        <div class="col-lg-6 text-right">
            <a href="" class="btn btn-sm btn-success" data-toggle="modal" data-target="#modal-projeto-cadastro"><i class="fa fa-plus"></i> Novo Projeto</a>
        </div>
        <div class="modal fade" id="modal-projeto-cadastro" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Novo Projeto</h4>
                    </div>
                    <div class="modal-body">
                        <?php echo $this->partial('projeto/form-projeto-cadastro.phtml', array("formProjetoCadastro" => $this->formProjetoCadastro)); ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- FIM NOVO CLIENTE -->
    </div>
    
    <!-- LISTA DE PROJETOS -->
    <div class="row">
        <div class="col-lg-12">
            <?php if ($this->projetos->getCurrentItemCount() > 0) : ?>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-6">Cliente</th>   
                            <th class="col-md-5">Projeto</th>                                                        
                            <th class="col-md-1 text-center"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->projetos as $projeto) : //Zend_Debug::dump($projeto); ?>
                        <tr>
                            <td>
                                <?php
                                    if ($projeto['cliente_tipo'] === 'PF') {
                                        echo $projeto['cliente_nome'];
                                    } else {
                                        echo $projeto['cliente_empresa'].' / '.$projeto['cliente_nome'];
                                    }
                                ?>
                            </td>  
                            <td><?php echo $projeto['projeto_nome']; ?></td>                                                        
                            <td>
                                <a href="<?php echo $this->url(array(
                                    'controller' => 'projeto',
                                    'action' => 'detalhes',
                                    'projeto' => $projeto['projeto_id']
                                ), null,true); ?>"><i class="fa fa-ellipsis-v"></i> Ver</a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>                    
                </table>
                <?php echo $this->paginationControl($this->projetos, 'Sliding', 'partials/pagination.phtml'); ?>
            </div>
            <?php else : ?>
            <div class="alert alert-warning">Nenhuma projeto cadastrado</div>            
            <?php endif; ?>
        </div>
    </div>
    
</section>