<section>
    
    <div class="row">
        <div class="col-lg-12">
            <h3>Proposta Detalhes</h3>   
        </div>
    </div>
    
    <!-- ACOES -->
    <div class="row">
        <div class="col-lg-12 text-right">            
            
            <?php if ($this->proposta->proposta_status === Site_PropostaController::STATUS_AGUARDANDO_RESPOSTA) : ?>
            <a href="<?php echo $this->url(array(
                'controller' => 'proposta',
                'action' => 'aprovar',
                'proposta' => $this->proposta->proposta_id
            ), null, true); ?>" class="btn btn-sm btn-success"><i class="fa fa-check fa-2x"></i></a>            
            
            <a href="<?php echo $this->url(array(
                'controller' => 'proposta',
                'action' => 'editar',
                'proposta' => $this->proposta->proposta_id
            ), null, true); ?>" class="btn btn-sm btn-info"><i class="fa fa-edit fa-2x"></i></a> 
    
    
            <a href="<?php echo $this->url(array(
                'controller' => 'proposta',
                'action' => 'excluir',
                'proposta' => $this->proposta->proposta_id
            ), null, true); ?>" class="btn btn-sm btn-danger"><i class="fa fa-trash fa-2x"></i></a>            
    
            <?php endif; ?>
            
            <hr />
        </div>
    </div>   
    
    <!-- DETALHES DA PROPOSTA -->
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <th>Status:</th>
                        <td colspan="5"><?php echo $this->proposta->proposta_status; ?></td>
                    <tr>
                        <th>Nº Proposta:</th>
                        <td><?php echo $this->proposta->proposta_numero; ?></td>
                        <th>Tipo Proposta:</th>
                        <td><?php echo $this->proposta->proposta_tipo_nome; ?></td>
                        <th>Tipo Servico:</th>
                        <td><?php echo $this->proposta->tipo_servico_nome; ?></td>
                    </tr>
                    <tr>
                        <th>Empresa/Cliente:</th>
                        <td colspan="5">
                            <?php if ($this->proposta->cliente_empresa) : ?>
                            <?php echo $this->proposta->cliente_empresa; ?>/
                            <?php echo $this->proposta->cliente_nome; ?>
                            <?php else : ?>
                            <?php echo $this->proposta->cliente_nome; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Horas:</th>
                        <td colspan="2"><?php echo $this->proposta->proposta_horas; ?></td>
                        <th>Valor:</th>                        
                        <td colspan="2"><?php echo $this->currency($this->proposta->proposta_valor); ?></td>
                    </tr>
                    <tr>
                        <th>Data:</th>
                        <td colspan="2"><?php echo App_Helper_Date::getDate($this->proposta->proposta_data); ?></td>
                        <th>Vencimento:</th>                        
                        <td colspan="2"><?php echo App_Helper_Date::getDate($this->proposta->proposta_vencimento); ?></td>
                    </tr>
                    <tr>
                        <th>Documento:</th>
                        <td colspan="5">
                            <a href="<?php echo $this->baseUrl(Zend_Registry::get("config")->proposta->filepath . '/' . $this->proposta->proposta_documento); ?>" target="_blank">
                                <i class="fa fa-file-pdf-o fa-2x"></i> <?php echo $this->proposta->proposta_documento; ?>
                            </a>
                        </td>
                    </tr>
                    
                </table>
            </div>
        </div>
    </div>
    
    <!-- ACOES -->
    <div class="row">
        <div class="col-lg-12 text-left">            
            <a href="<?php echo $this->url(array(
                'controller' => 'proposta',
                'action' => 'reenviar',
                'proposta' => $this->proposta->proposta_id
            ), null, true); ?>" class="btn btn-sm btn-warning"><i class="fa fa-send fa-2x"></i></a>
    
        </div>
    </div> 
    
</section>