<section>
    <form method="post" action="<?php echo $this->url(array(
        'controller' => 'proposta',
        'action' => 'cadastro'
    ), null, true); ?>" id="form-proposta-cadastro" enctype="multipart/form-data">
        <div class="row">
            <div class="form-group">
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->proposta_numero; ?></div>
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->proposta_tipo_id; ?></div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->cliente_id; ?></div>
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->tipo_servico_id; ?></div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->proposta_horas; ?></div>
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->proposta_valor; ?></div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->proposta_data; ?></div>
                <div class="col-lg-6"><?php echo $this->formPropostaCadastro->proposta_vencimento; ?></div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-lg-12"><?php echo $this->formPropostaCadastro->proposta_documento; ?></div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-lg-12"><?php echo $this->formPropostaCadastro->submit; ?></div>
            </div>
        </div>
    </form>
</section>